context:
  version: "0.2.0"

package:
  name: "nvmolkit"
  version: ${{ version }}

source:
  url: https://github.com/NVIDIA-Digital-Bio/nvMolKit/archive/v${{ version }}.tar.gz
  sha256: 8c0181c4dcd02aac42dc3c1b783ac677a8149fd5d5b5d25e85ba30e85bd6ec5a

build:
  number: 1
  skip:
    - osx
    - win
    - cuda_compiler_version == "None"
requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('cuda') }}
    - cmake >=3.30
    - make
  host:
    - cuda-version ${{ cuda_compiler_version }}.*
    - cuda-cudart-dev
    - cuda-nvtx-dev
    - eigen
    - libboost-devel
    - libboost-headers
    - libboost-python-devel
    - libcublas-dev
    - libcurand-dev
    - libcusolver-dev
    - libgomp
    - librdkit-dev ==${{ librdkit_dev }}
    - pip
    - python
    - rdkit
    - scikit-build
    - setuptools
  run:
    - numpy
    - python
    - pytorch
    - rdkit ==${{ librdkit_dev }}

tests:
  - python:
      imports:
        - nvmolkit

about:
  homepage: https://github.com/NVIDIA-Digital-Bio/nvMolKit
  summary: nvMolKit is a CUDA-backed python library for accelerating common RDKit molecular operations
  description: |
    nvMolKit is a CUDA-backed python library for accelerating common RDKit molecular operations.
    nvMolKit links to RDKit and nvMolKit operations work on RDKit RDMol objects.
  license_file: LICENSE/License.txt
  license: Apache-2.0

extra:
  recipe-maintainers:
    - evasnow1992
    - scal444
