context:
  # Conda version (no hyphen allowed); use _ for pre-release
  version: "0.4.0_test"
  # GitHub tag for source tarball (can contain -)
  git_tag: "0.4.0-test"

package:
  name: "nvmolkit"
  version: ${{ version }}

source:
  url: https://github.com/evasnow1992/nvMolKit/archive/v${{ git_tag }}.tar.gz
  sha256: b3e8f0d184c546e4e47fc3d3913f95357bd523089bb3ce518ffb31e8690f8feb

build:
  number: 0
  skip:
    - osx
    - win
    - cuda_compiler_version == "None"
requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('cuda') }}
    - cmake >=3.30
    - make
  host:
    - cuda-version ${{ cuda_compiler_version }}.*
    - cuda-cudart-dev
    - cuda-nvtx-dev
    - eigen
    - libboost-devel
    - libboost-headers
    - libboost-python-devel
    - libcublas-dev
    - libcurand-dev
    - libcusolver-dev
    - libgomp
    - librdkit-dev ==${{ librdkit_dev }}
    - pip
    - python
    - rdkit
    - scikit-build
    - setuptools
  run:
    - numpy
    - python
    - pytorch
    - rdkit ==${{ librdkit_dev }}

tests:
  - python:
      imports:
        - nvmolkit

about:
  homepage: https://github.com/NVIDIA-Digital-Bio/nvMolKit
  summary: nvMolKit is a CUDA-backed python library for accelerating common RDKit molecular operations
  description: |
    nvMolKit is a CUDA-backed python library for accelerating common RDKit molecular operations.
    nvMolKit links to RDKit and nvMolKit operations work on RDKit RDMol objects.
  license_file: LICENSE/License.txt
  license: Apache-2.0

extra:
  recipe-maintainers:
    - evasnow1992
    - scal444
